name: flutter_motion1
description: "A new Flutter project."
publish_to: "none" # Private package, won't be published to pub.dev

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Mendukung rentang versi Dart SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "00623B"
  image: assets/logos/Splash-Logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Profile-image.png
    - assets/images/Jam.png
    - assets/images/IconShop.png
    - assets/images/Sepatu.png
    - assets/images/Headset.png
    - assets/images/Baju.png
    - assets/lottie/lottie_login.json
    - assets/lottie/lottie_checklist.json
    - assets/logos/Splash-Logo.png
